# Hugo configuration file
baseURL = 'https://semihb.com/'
languageCode = 'en-us'
title = 'semih berkay öztürk'
theme = 'archie'
[params]
	mode="dark"
	useCDN=false
	subtitle="some cached thoughts on technology, startups, and more."
	
[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "writings"
url = "/essays"
weight = 2

[[menu.main]]
name = "bookmarks"
url = "/bookmarks"
weight = 3

[[menu.main]]
name = "about"
url = "/about"
weight = 4

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/semioz/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/semioz/"

[[params.social]]
name = "X"
icon = "x"
url = "https://x.com/semiozz"

[caches]
  [caches.images]
    dir = ':cacheDir/images'